# Generated by Django 6.0.6 on 2026-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('salon_admin', '0003_role_all_centers_role_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='users', to='salon_admin.center'),
        ),
    ]
