# Generated by Django 6.0.6 on 2026-07-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_centers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='centers',
        ),
    ]
