# Generated by Django 6.0.6 on 2026-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_centers'),
        ('salon_admin', '0004_remove_role_all_centers_remove_role_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='users', to='salon_admin.center'),
        ),
    ]
