# Generated by Django 6.0.6 on 2026-07-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('Discount', 'Discount on Bill/items'), ('FlatPrice', 'Flat Price on items'), ('Trigger', 'Trigger Deals'), ('Cashback', 'Cashback Cards')], default='Discount', max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bill_amount_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_amount_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue_generated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon_admin.center')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketing.promotion')),
            ],
        ),
    ]
