# Generated by Django 6.0.6 on 2026-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_promotion_config_promotion_promo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='max_usage_per_client',
            field=models.IntegerField(blank=True, help_text='Limit per client. Leave blank for unlimited.', null=True),
        ),
    ]
