# Generated by Django 6.0.6 on 2026-07-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_promotion_max_usage_per_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='valuecard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
