# Generated by Django 6.0.6 on 2026-07-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_package_is_active_valuecard_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='services_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
