# Generated by Django 4.2.30 on 2026-07-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_gender'),
        ('marketing', '0005_package_services_json_alter_package_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionusage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='clients.client'),
        ),
    ]
