# Generated by Django 4.2.30 on 2026-07-28 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_promotionusage_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='expiry_days',
            field=models.IntegerField(help_text='Must be at least 1 day.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='validity_days',
            field=models.IntegerField(help_text='Must be at least 1 day.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='valuecard',
            name='expiry_days',
            field=models.IntegerField(help_text='Must be at least 1 day.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
