# Generated by Django 5.2.3 on 2026-08-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_invoice_finalized_at_invoice_idempotency_key_and_more'),
        ('marketing', '0008_remove_membership_price_membership_incentive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionusage',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_usages', to='billing.invoice'),
        ),
    ]
