# Generated by Django 4.2.30 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_remove_membership_price_membership_incentive_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['is_active'], name='mbr_active_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['created_at'], name='mbr_created_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active'], name='pkg_active_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['created_at'], name='pkg_created_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='promo_active_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['created_at'], name='promo_created_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['promotion', 'center'], name='promo_usage_center_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['client'], name='promo_usage_client_idx'),
        ),
        migrations.AddIndex(
            model_name='valuecard',
            index=models.Index(fields=['is_active'], name='vc_active_idx'),
        ),
        migrations.AddIndex(
            model_name='valuecard',
            index=models.Index(fields=['created_at'], name='vc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['center', 'created_at'], name='wa_center_date_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['status'], name='wa_status_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['created_at'], name='wa_created_idx'),
        ),
    ]
