# Generated by Django 4.2.30 on 2026-08-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['name']},
        ),
    ]
