# Generated by Django 6.0.6 on 2026-07-11 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_cgst_invoice_discount_invoice_rounding_and_more'),
        ('staff', '0010_stafftransfer_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='invoice_items_multi', to='staff.staffmember'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
        ),
    ]
