# Generated by Django 6.0.6 on 2026-07-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoiceitem_staff_members_payment'),
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='salon_admin.center'),
        ),
    ]
