# Generated by Django 6.0.6 on 2026-07-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_inv_status_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Google Pay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Paytm', 'Paytm'), ('BharatPe', 'BharatPe'), ('Cheque', 'Cheque'), ('Net Banking', 'Net Banking'), ('NearBuy', 'NearBuy'), ('Advance', 'Advance'), ('Other', 'Other')], default='Cash', max_length=50),
        ),
    ]
