# Generated by Django 6.0.6 on 2026-07-14 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_advancepayment_invoice_alter_payment_payment_method'),
        ('clients', '0003_clientmembership_clientpackage_clientvaluecard'),
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
        ('staff', '0012_payrollrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billchangelog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='value_card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['client', 'created_at'], name='adv_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='billchangelog',
            index=models.Index(fields=['center', 'created_at'], name='changelog_center_date_idx'),
        ),
        migrations.AddIndex(
            model_name='billchangelog',
            index=models.Index(fields=['invoice'], name='changelog_invoice_idx'),
        ),
    ]
