# Generated by Django 6.0.6 on 2026-07-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billchangelog_notes_payment_value_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
