# Generated by Django 6.0.6 on 2026-07-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_tip_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Google Pay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Paytm', 'Paytm'), ('BharatPe', 'BharatPe'), ('Cheque', 'Cheque'), ('Net Banking', 'Net Banking'), ('NearBuy', 'NearBuy'), ('Advance', 'Advance'), ('Value Card', 'Value Card'), ('Other', 'Other')], default='Cash', max_length=50),
        ),
    ]
