# Generated by Django 4.2.30 on 2026-07-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_gender'),
        ('billing', '0010_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Google Pay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Paytm', 'Paytm'), ('BharatPe', 'BharatPe'), ('Cheque', 'Cheque'), ('Net Banking', 'Net Banking'), ('NearBuy', 'NearBuy'), ('Advance', 'Advance'), ('Value Card', 'Value Card'), ('Cashback Wallet', 'Cashback Wallet'), ('Other', 'Other')], default='Cash', max_length=50),
        ),
        migrations.CreateModel(
            name='CashbackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_transactions', to='clients.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_transactions', to='billing.invoice')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'created_at'], name='cb_client_date_idx')],
            },
        ),
    ]
