# Generated by Django 4.2.30 on 2026-07-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_date'),
        ('billing', '0013_alter_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='appointments.appointment'),
        ),
    ]
