# Generated by Django 4.2.30 on 2026-08-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_invoiceitem_tax_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['center', 'status', 'created_at'], name='inv_center_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='inv_client_status_idx'),
        ),
    ]
