# Generated by Django 5.2.3 on 2026-08-06 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_invoice_inv_center_status_date_idx_and_more'),
        ('clients', '0008_client_app_pin_hash_length'),
        ('marketing', '0008_remove_membership_price_membership_incentive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.clientmembership'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='marketing.promotion'),
        ),
        migrations.CreateModel(
            name='InvoiceRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_method', models.CharField(choices=[('Cash', 'Cash'), ('Original', 'Original Payment Method'), ('UPI', 'UPI'), ('Card', 'Card'), ('Other', 'Other')], default='Original', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.invoice')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice', 'created_at'], name='refund_invoice_date_idx')],
            },
        ),
    ]
