# Generated by Django 4.2.30 on 2026-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_invoice_inv_center_status_date_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'content_type'], name='invoiceitem_inv_ct_idx'),
        ),
    ]
