# Generated by Django 4.2.30 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_invoiceitem_inv_ct_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoiceitem',
            name='invoiceitem_inv_ct_idx',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='pay_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'created_at'], name='pay_method_date_idx'),
        ),
    ]
