# Generated by Django 4.2.30 on 2026-08-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_complimentary',
            field=models.BooleanField(default=False, help_text='Flags 0-value items intentionally given for free or redeemed'),
        ),
    ]
