# Generated by Django 4.2.30 on 2026-08-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_invoicerefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='manager_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
