[program:pos_backend]
command=%(ENV_POS_BACKEND_DIR)s/.venv/bin/gunicorn -c gunicorn.conf.py pos_backend.wsgi:application
directory=%(ENV_POS_BACKEND_DIR)s
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/pos_backend.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=DJANGO_DEBUG="False"
