# Generated by Django 6.0.6 on 2026-07-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=255, verbose_name='Center / Legal Name')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('cst_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='CST Number')),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pan Number')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_email_3', models.EmailField(blank=True, max_length=254, null=True)),
                ('accountant_email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('accountant_email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('launched_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
