# Generated by Django 6.0.6 on 2026-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0002_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='all_centers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='roles', to='salon_admin.center'),
        ),
    ]
