# Generated by Django 6.0.6 on 2026-07-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0003_role_all_centers_role_centers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='all_centers',
        ),
        migrations.RemoveField(
            model_name='role',
            name='centers',
        ),
    ]
