# Generated by Django 6.0.6 on 2026-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0004_remove_role_all_centers_remove_role_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='accountant_name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='accountant_name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='accountant_phone_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='accountant_phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='center',
            name='monthly_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='owner_name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='owner_name_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='owner_phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='owner_phone_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
