# Generated by Django 6.0.6 on 2026-07-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0005_center_accountant_name_1_center_accountant_name_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='closing_sms_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='center',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='center',
            name='gst_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='center',
            name='monthly_targets_history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
