# Generated by Django 4.2.30 on 2026-08-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='phone_2',
            new_name='landline_1',
        ),
        migrations.AddField(
            model_name='center',
            name='center_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='landline_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
