# Generated by Django 4.2.30 on 2026-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0007_rename_phone_2_center_landline_1_center_center_email_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['created_at'], name='center_created_idx'),
        ),
    ]
