# Generated by Django 4.2.30 on 2026-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0008_add_remaining_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
