# Generated by Django 6.0.6 on 2026-07-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['center', 'date'], name='appt_center_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appt_status_idx'),
        ),
    ]
