# Generated by Django 6.0.6 on 2026-07-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_appt_center_date_idx_and_more'),
        ('clients', '0003_clientmembership_clientpackage_clientvaluecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clients.client'),
        ),
    ]
