# Generated by Django 4.2.30 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='appt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['center', 'status'], name='appt_center_status_idx'),
        ),
    ]
