# Generated by Django 4.2.30 on 2026-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointmentservice',
            index=models.Index(fields=['staff', 'appointment'], name='appointment_staff_i_7489ce_idx'),
        ),
    ]
