# Generated by Django 4.2.30 on 2026-07-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='center_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='center_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='human_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='module',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
