# Generated by Django 4.2.30 on 2026-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_systemlog_center_id_systemlog_center_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['-timestamp'], name='audit_logs__timesta_3750c1_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['action'], name='audit_logs__action_eb30ae_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['module'], name='audit_logs__module_416c90_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['center_id'], name='audit_logs__center__2709fe_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user_email'], name='audit_logs__user_em_e146c4_idx'),
        ),
    ]
