# Generated by Django 4.2.30 on 2026-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_systemlog_audit_logs__timesta_3750c1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='geo_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='geo_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='geo_country_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='geo_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='os_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
