# Generated by Django 4.2.30 on 2026-07-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0004_systemlog_browser_systemlog_device_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['module', 'action'], name='syslog_module_action_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['center_id', 'timestamp'], name='syslog_center_ts_idx'),
        ),
    ]
