# Generated by Django 6.0.6 on 2026-07-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon_admin', '0002_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('sac_code', models.CharField(blank=True, max_length=50, null=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_mins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CenterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon_admin.center')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_overrides', to='services.servicemaster')),
            ],
            options={
                'unique_together': {('center', 'service')},
            },
        ),
    ]
