# Generated by Django 6.0.6 on 2026-07-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0004_remove_role_all_centers_remove_role_centers'),
        ('services', '0002_add_scope_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemaster',
            name='center',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='scope',
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='assigned_services', to='salon_admin.center'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='level',
            field=models.CharField(choices=[('Organisation', 'Organisation'), ('Center', 'Center Specific')], default='Organisation', max_length=20),
        ),
    ]
