# Generated by Django 4.2.30 on 2026-07-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicemaster_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemaster',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='service_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
