# Generated by Django 4.2.30 on 2026-08-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicemaster_brand_servicemaster_hsn_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemaster',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Incentive %'),
        ),
    ]
