# Generated by Django 4.2.30 on 2026-08-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicemaster_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerservice',
            name='incentive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Incentive % (Center Override)'),
        ),
        migrations.AddIndex(
            model_name='centerservice',
            index=models.Index(fields=['center', 'is_active'], name='cs_center_active_idx'),
        ),
    ]
