# Generated by Django 4.2.30 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_centerservice_incentive_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='centerservice',
            index=models.Index(fields=['service'], name='cs_service_idx'),
        ),
        migrations.AddIndex(
            model_name='centerservice',
            index=models.Index(fields=['created_at'], name='cs_created_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemaster',
            index=models.Index(fields=['category'], name='svc_category_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemaster',
            index=models.Index(fields=['created_at'], name='svc_created_idx'),
        ),
    ]
