# Generated by Django 4.2.30 on 2026-08-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemaster',
            options={'ordering': ['name']},
        ),
    ]
