# Generated by Django 6.0.6 on 2026-07-12 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('use_multiple', models.BooleanField(default=False)),
                ('use_custom_percent', models.BooleanField(default=True)),
                ('custom_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incentive_configs', to='salon_admin.center')),
            ],
        ),
        migrations.CreateModel(
            name='PettyCashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_entries', to='salon_admin.center')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('todays_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paytm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bharat_pe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cheque_netbanking', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('google_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('phone_pe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nearbuy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closings', to='salon_admin.center')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('center', 'date')},
            },
        ),
    ]
