# Generated by Django 6.0.6 on 2026-07-12 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pettycashentry',
            index=models.Index(fields=['center', 'date'], name='petty_center_date_idx'),
        ),
    ]
