# Generated by Django 6.0.6 on 2026-07-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_pettycashentry_petty_center_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='upi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
