# Generated by Django 4.2.30 on 2026-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='system_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
