# Generated by Django 4.2.30 on 2026-07-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_dailyclosing_difference_dailyclosing_system_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_multiple', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Min Salary Multiple (x)')),
                ('incentive_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Incentive % of Revenue')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='finance.incentiveconfig')),
            ],
            options={
                'ordering': ['min_multiple'],
                'unique_together': {('config', 'min_multiple')},
            },
        ),
    ]
