# Generated by Django 4.2.30 on 2026-08-03 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
        ('finance', '0006_incentivetier'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly Basis'), ('daily', 'Daily Basis')], default='monthly', max_length=20)),
                ('category', models.CharField(choices=[('value_cards', 'Value Cards'), ('products', 'Products'), ('services', 'Services'), ('memberships', 'Memberships'), ('packages', 'Packages'), ('overall', 'Overall Business')], default='products', max_length=50)),
                ('rule_type', models.CharField(choices=[('slab', 'Fixed Slab / Range Reward'), ('multiple', 'Business / Salary Multiplier Tiers'), ('percentage', 'Flat Percentage'), ('flat', 'Flat Amount')], default='multiple', max_length=50)),
                ('applicable_role', models.CharField(choices=[('all', 'All Managers and Staff'), ('staff', 'Staff Only'), ('manager', 'Managers Only')], default='all', max_length=50)),
                ('tiers', models.JSONField(blank=True, default=list)),
                ('flat_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('effective_from', models.DateField(blank=True, help_text='Date from which this rule applies.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this rule applies (optional for ongoing).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incentive_rules', to='salon_admin.center')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
