# Generated by Django 4.2.30 on 2026-08-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_incentiverule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiverule',
            name='applicable_role',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='category',
            field=models.CharField(default='services', max_length=60),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='frequency',
            field=models.CharField(default='monthly', max_length=30),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='rule_type',
            field=models.CharField(default='multiple', max_length=60),
        ),
    ]
