# Generated by Django 4.2.30 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_incentiverule_applicable_role_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyclosing',
            index=models.Index(fields=['center', 'date'], name='dc_center_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyclosing',
            index=models.Index(fields=['created_at'], name='dc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='incentiverule',
            index=models.Index(fields=['center', 'is_active'], name='ir_center_active_idx'),
        ),
        migrations.AddIndex(
            model_name='incentiverule',
            index=models.Index(fields=['is_active', 'category'], name='ir_active_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='incentiverule',
            index=models.Index(fields=['created_at'], name='ir_created_idx'),
        ),
    ]
