# Generated by Django 6.0.6 on 2026-07-05 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon_admin', '0002_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Retail', 'Retail'), ('Professional', 'Professional')], default='Retail', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (incl. tax)')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('sac_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='SAC Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='salon_admin.center')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('cst_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='CST Number')),
                ('pan_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='PAN Number')),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='salon_admin.center')),
            ],
        ),
    ]
