# Generated by Django 6.0.6 on 2026-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_reorder_level_product_reorder_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='Current Stock'),
        ),
    ]
