# Generated by Django 6.0.6 on 2026-07-12 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_current_stock'),
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CHECKOUT', 'Checkout for salon use'), ('AUDIT', 'Stock Audit Adjustment'), ('PO_RECEIPT', 'Purchase Order Receipt'), ('SALE', 'Retail Sale'), ('REFUND', 'Refunded Sale')], max_length=50)),
                ('quantity_change', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='salon_admin.center')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product')),
            ],
        ),
    ]
