# Generated by Django 4.2.30 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_vendor_city_vendor_pin_code_vendor_state_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['center', 'is_active'], name='product_center_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_category_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='product_created_idx'),
        ),
        migrations.AddIndex(
            model_name='productlot',
            index=models.Index(fields=['product'], name='lot_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productlot',
            index=models.Index(fields=['created_at'], name='lot_created_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['center', 'status'], name='po_center_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'created_at'], name='po_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='po_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['center', 'created_at'], name='stock_center_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['product', 'created_at'], name='stock_product_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='stock_type_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['center'], name='vendor_center_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['created_at'], name='vendor_created_idx'),
        ),
    ]
