# Generated by Django 6.0.6 on 2026-07-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_center'),
        ('marketing', '0005_package_services_json_alter_package_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clients.client')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.membership')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_remaining', models.JSONField(default=dict, help_text='Maps service_id or name to remaining quantity')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clients.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.package')),
            ],
        ),
        migrations.CreateModel(
            name='ClientValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_cards', to='clients.client')),
                ('value_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.valuecard')),
            ],
        ),
    ]
