# Generated by Django 6.0.6 on 2026-07-14 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientmembership_clientpackage_clientvaluecard'),
        ('marketing', '0005_package_services_json_alter_package_service_name'),
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpackage',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.package'),
        ),
        migrations.AlterField(
            model_name='clientpackage',
            name='services_remaining',
            field=models.JSONField(default=dict, help_text='Maps service_id to remaining quantity'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='client_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['center'], name='client_center_idx'),
        ),
    ]
