# Generated by Django 4.2.30 on 2026-07-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientpackage_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, default='female', max_length=20, null=True),
        ),
    ]
