# Generated by Django 4.2.30 on 2026-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
