# Generated by Django 4.2.30 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='client_created_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['center', 'created_at'], name='client_center_date_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['gender'], name='client_gender_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmembership',
            index=models.Index(fields=['client'], name='cm_client_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmembership',
            index=models.Index(fields=['is_active'], name='cm_active_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmembership',
            index=models.Index(fields=['created_at'], name='cm_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackage',
            index=models.Index(fields=['client'], name='cpkg_client_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackage',
            index=models.Index(fields=['is_active'], name='cpkg_active_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpackage',
            index=models.Index(fields=['created_at'], name='cpkg_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvaluecard',
            index=models.Index(fields=['client'], name='cvc_client_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvaluecard',
            index=models.Index(fields=['is_active'], name='cvc_active_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvaluecard',
            index=models.Index(fields=['created_at'], name='cvc_created_idx'),
        ),
    ]
