# Generated by Django 5.2.3 on 2026-08-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_invoice_finalized_at_invoice_idempotency_key_and_more'),
        ('clients', '0008_client_app_pin_hash_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmembership',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_memberships', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='clientpackage',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_packages', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='clientvaluecard',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_value_cards', to='billing.invoice'),
        ),
        migrations.CreateModel(
            name='PackageRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_redemptions', to='billing.invoice')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='clients.clientpackage')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice', 'service_id'], name='pkg_red_invoice_service_idx')],
            },
        ),
    ]
