# Generated by Django 4.2.30 on 2026-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='app_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
