# Generated by Django 4.2.30 on 2026-08-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_invoicerefund'),
        ('clients', '0010_alter_client_app_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmembership',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='clientpackage',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='clientvaluecard',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice'),
        ),
    ]
