# Generated by Django 4.2.30 on 2026-08-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientmembership_source_invoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['first_name']},
        ),
    ]
