# Generated by Django 6.0.6 on 2026-07-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon_admin', '0002_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Female', max_length=20)),
                ('designation', models.CharField(max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('app_password', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='salon_admin.center')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('Service', 'Service'), ('Package', 'Package'), ('Membership', 'Membership'), ('Product', 'Product')], default='Service', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='salon_admin.center')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='staff.staffmember')),
            ],
        ),
    ]
