# Generated by Django 6.0.6 on 2026-07-06 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('staff', '0002_staffmember_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='billing.invoice'),
        ),
    ]
