# Generated by Django 6.0.6 on 2026-07-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_servicelog_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission % for services', max_digits=5),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='product_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission % for products', max_digits=5),
        ),
    ]
