# Generated by Django 6.0.6 on 2026-07-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffmember_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='product_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
