# Generated by Django 6.0.6 on 2026-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffmember_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='allocated_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Perk Points'),
        ),
    ]
