# Generated by Django 6.0.6 on 2026-07-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
        ('staff', '0006_staffmember_allocated_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffConsumptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('payment_method', models.CharField(choices=[('Points', 'Allocated Points'), ('Money', 'Own Money')], default='Points', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_consumptions', to='salon_admin.center')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_logs', to='staff.staffmember')),
            ],
        ),
    ]
