# Generated by Django 6.0.6 on 2026-07-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
        ('staff', '0007_staffconsumptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='StaffToolTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('date_taken', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Taken', 'Taken'), ('Returned', 'Returned')], default='Taken', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_tracked', to='staff.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='StaffTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('Temporary', 'Temporary'), ('Permanent', 'Permanent')], default='Permanent', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='salon_admin.center')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='staff.staffmember')),
                ('to_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='salon_admin.center')),
            ],
        ),
    ]
