# Generated by Django 6.0.6 on 2026-07-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staffmember_salary_stafftooltracker_stafftransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftooltracker',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Item Details'),
        ),
        migrations.AlterField(
            model_name='stafftooltracker',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Quantity/Amount'),
        ),
        migrations.AlterField(
            model_name='stafftooltracker',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_trackers', to='staff.staffmember'),
        ),
    ]
