# Generated by Django 6.0.6 on 2026-07-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_stafftooltracker_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftransfer',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
