# Generated by Django 6.0.6 on 2026-07-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_inv_status_date_idx_and_more'),
        ('salon_admin', '0006_center_closing_sms_recipients_center_credit_limit_and_more'),
        ('staff', '0010_stafftransfer_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['staff', 'date'], name='slog_staff_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['center', 'date'], name='slog_center_date_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['invoice'], name='slog_invoice_idx'),
        ),
    ]
