# Generated by Django 4.2.30 on 2026-07-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_payment_payment_method'),
        ('staff', '0012_payrollrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_logs', to='billing.invoice'),
        ),
    ]
