# Generated by Django 4.2.30 on 2026-08-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='staff_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Code'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
