# Generated by Django 4.2.30 on 2026-08-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_staffmember_address_staffmember_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='designation_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.designation', verbose_name='Designation (Master)'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['center'], name='slog_center_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['date'], name='slog_date_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['center'], name='staff_center_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['is_active'], name='staff_active_idx'),
        ),
    ]
