# Generated by Django 4.2.30 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_staffmember_designation_fk_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payrollrecord',
            new_name='payroll_center_month_idx',
            old_name='staff_payro_center__b7cd7a_idx',
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['created_at'], name='desig_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['status'], name='payroll_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['created_at'], name='payroll_created_idx'),
        ),
        migrations.AddIndex(
            model_name='staffconsumptionlog',
            index=models.Index(fields=['staff', 'date'], name='scon_staff_date_idx'),
        ),
        migrations.AddIndex(
            model_name='staffconsumptionlog',
            index=models.Index(fields=['center', 'date'], name='scon_center_date_idx'),
        ),
        migrations.AddIndex(
            model_name='staffconsumptionlog',
            index=models.Index(fields=['created_at'], name='scon_created_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['center', 'is_active'], name='staff_center_active_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['created_at'], name='staff_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftooltracker',
            index=models.Index(fields=['staff'], name='tool_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftooltracker',
            index=models.Index(fields=['status'], name='tool_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftooltracker',
            index=models.Index(fields=['created_at'], name='tool_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftransfer',
            index=models.Index(fields=['staff'], name='stransfer_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftransfer',
            index=models.Index(fields=['status'], name='stransfer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftransfer',
            index=models.Index(fields=['created_at'], name='stransfer_created_idx'),
        ),
    ]
