# Generated by Django 4.2.30 on 2026-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['created_at'], name='slog_created_idx'),
        ),
    ]
