# Generated by Django 4.2.30 on 2026-08-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_add_remaining_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['center', 'date', 'staff'], name='slog_center_date_staff_idx'),
        ),
    ]
